/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccesoRouteImport } from './routes/acceso'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CanjearCodigoRouteImport } from './routes/canjear-codigo'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as CertificadosRouteImport } from './routes/certificados'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as DudasRouteImport } from './routes/dudas'
import { Route as EmpresaRouteImport } from './routes/empresa'
import { Route as EmpresasRouteImport } from './routes/empresas'
import { Route as FacturasRouteImport } from './routes/facturas'
import { Route as FormacionPreventivaOficialRouteImport } from './routes/formacion-preventiva-oficial'
import { Route as MisCursosRouteImport } from './routes/mis-cursos'
import { Route as NuevaContrasenaRouteImport } from './routes/nueva-contrasena'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as RecuperarContrasenaRouteImport } from './routes/recuperar-contrasena'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as SobreNosotrosRouteImport } from './routes/sobre-nosotros'
import { Route as VerificarCertificadoRouteImport } from './routes/verificar-certificado'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAdminSectionRouteImport } from './routes/admin.$adminSection'
import { Route as AdminCodigosRouteImport } from './routes/admin.codigos'
import { Route as AdminCursosRouteImport } from './routes/admin.cursos'
import { Route as AdminEvaluacionesRouteImport } from './routes/admin.evaluaciones'
import { Route as AdminFacturacionRouteImport } from './routes/admin.facturacion'
import { Route as AdminMensajesRouteImport } from './routes/admin.mensajes'
import { Route as AdminPracticasRouteImport } from './routes/admin.practicas'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as ApiAdminBillingRouteImport } from './routes/api.admin-billing'
import { Route as ApiCertificadoStvhRouteImport } from './routes/api.certificado-stvh'
import { Route as ApiCheckoutRouteImport } from './routes/api.checkout'
import { Route as ApiCompanyAccessCodesRouteImport } from './routes/api.company-access-codes'
import { Route as ApiInvoicesRouteImport } from './routes/api.invoices'
import { Route as ApiPaymentStatusRouteImport } from './routes/api.payment-status'
import { Route as ApiStripeWebhookRouteImport } from './routes/api.stripe-webhook'
import { Route as CampusEnrollmentIdRouteImport } from './routes/campus.$enrollmentId'
import { Route as ComprarEmpresaCourseSlugRouteImport } from './routes/comprar-empresa.$courseSlug'
import { Route as ComprarCourseSlugRouteImport } from './routes/comprar.$courseSlug'
import { Route as CursosCourseSlugRouteImport } from './routes/cursos.$courseSlug'
import { Route as DudasIndexRouteImport } from './routes/dudas.index'
import { Route as DudasThreadIdRouteImport } from './routes/dudas.$threadId'
import { Route as EmpresaIndexRouteImport } from './routes/empresa.index'
import { Route as EmpresaCompanySectionRouteImport } from './routes/empresa.$companySection'
import { Route as EmpresaCodigosRouteImport } from './routes/empresa.codigos'
import { Route as LegalLegalSlugRouteImport } from './routes/legal.$legalSlug'
import { Route as PagoConfirmadoRouteImport } from './routes/pago.confirmado'
import { Route as AdminCursosIndexRouteImport } from './routes/admin.cursos.index'
import { Route as AdminCursosCourseIdRouteImport } from './routes/admin.cursos.$courseId'
import { Route as ApiCronBillingRouteImport } from './routes/api.cron.billing'
import { Route as CampusEnrollmentIdIndexRouteImport } from './routes/campus.$enrollmentId.index'
import { Route as CampusEnrollmentIdConfidencialidadRouteImport } from './routes/campus.$enrollmentId.confidencialidad'
import { Route as EvaluacionEnrollmentIdQuizIdRouteImport } from './routes/evaluacion.$enrollmentId.$quizId'
import { Route as ApiInternalArchivePendingRouteImport } from './routes/api.internal.archive.pending'
import { Route as ApiInvoicesInvoiceIdDownloadRouteImport } from './routes/api.invoices.$invoiceId.download'
import { Route as CampusEnrollmentIdLeccionLessonIdRouteImport } from './routes/campus.$enrollmentId.leccion.$lessonId'
import { Route as ApiAdminBillingRetryInvoiceIdRouteImport } from './routes/api.admin.billing.retry.$invoiceId'
import { Route as ApiInternalArchiveInvoiceIdConfirmRouteImport } from './routes/api.internal.archive.$invoiceId.confirm'
import { Route as ApiInternalArchiveInvoiceIdDownloadRouteImport } from './routes/api.internal.archive.$invoiceId.download'
import { Route as ApiInternalArchiveInvoiceIdFailRouteImport } from './routes/api.internal.archive.$invoiceId.fail'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccesoRoute = AccesoRouteImport.update({
  id: '/acceso',
  path: '/acceso',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CanjearCodigoRoute = CanjearCodigoRouteImport.update({
  id: '/canjear-codigo',
  path: '/canjear-codigo',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificadosRoute = CertificadosRouteImport.update({
  id: '/certificados',
  path: '/certificados',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const DudasRoute = DudasRouteImport.update({
  id: '/dudas',
  path: '/dudas',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaRoute = EmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasRoute = EmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturasRoute = FacturasRouteImport.update({
  id: '/facturas',
  path: '/facturas',
  getParentRoute: () => rootRouteImport,
} as any)
const FormacionPreventivaOficialRoute =
  FormacionPreventivaOficialRouteImport.update({
    id: '/formacion-preventiva-oficial',
    path: '/formacion-preventiva-oficial',
    getParentRoute: () => rootRouteImport,
  } as any)
const MisCursosRoute = MisCursosRouteImport.update({
  id: '/mis-cursos',
  path: '/mis-cursos',
  getParentRoute: () => rootRouteImport,
} as any)
const NuevaContrasenaRoute = NuevaContrasenaRouteImport.update({
  id: '/nueva-contrasena',
  path: '/nueva-contrasena',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarContrasenaRoute = RecuperarContrasenaRouteImport.update({
  id: '/recuperar-contrasena',
  path: '/recuperar-contrasena',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreNosotrosRoute = SobreNosotrosRouteImport.update({
  id: '/sobre-nosotros',
  path: '/sobre-nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificarCertificadoRoute = VerificarCertificadoRouteImport.update({
  id: '/verificar-certificado',
  path: '/verificar-certificado',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminSectionRoute = AdminAdminSectionRouteImport.update({
  id: '/$adminSection',
  path: '/$adminSection',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCodigosRoute = AdminCodigosRouteImport.update({
  id: '/codigos',
  path: '/codigos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCursosRoute = AdminCursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEvaluacionesRoute = AdminEvaluacionesRouteImport.update({
  id: '/evaluaciones',
  path: '/evaluaciones',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFacturacionRoute = AdminFacturacionRouteImport.update({
  id: '/facturacion',
  path: '/facturacion',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMensajesRoute = AdminMensajesRouteImport.update({
  id: '/mensajes',
  path: '/mensajes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPracticasRoute = AdminPracticasRouteImport.update({
  id: '/practicas',
  path: '/practicas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAdminBillingRoute = ApiAdminBillingRouteImport.update({
  id: '/api/admin-billing',
  path: '/api/admin-billing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCertificadoStvhRoute = ApiCertificadoStvhRouteImport.update({
  id: '/api/certificado-stvh',
  path: '/api/certificado-stvh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutRoute = ApiCheckoutRouteImport.update({
  id: '/api/checkout',
  path: '/api/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompanyAccessCodesRoute = ApiCompanyAccessCodesRouteImport.update({
  id: '/api/company-access-codes',
  path: '/api/company-access-codes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvoicesRoute = ApiInvoicesRouteImport.update({
  id: '/api/invoices',
  path: '/api/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentStatusRoute = ApiPaymentStatusRouteImport.update({
  id: '/api/payment-status',
  path: '/api/payment-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe-webhook',
  path: '/api/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusEnrollmentIdRoute = CampusEnrollmentIdRouteImport.update({
  id: '/campus/$enrollmentId',
  path: '/campus/$enrollmentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprarEmpresaCourseSlugRoute =
  ComprarEmpresaCourseSlugRouteImport.update({
    id: '/comprar-empresa/$courseSlug',
    path: '/comprar-empresa/$courseSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComprarCourseSlugRoute = ComprarCourseSlugRouteImport.update({
  id: '/comprar/$courseSlug',
  path: '/comprar/$courseSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosCourseSlugRoute = CursosCourseSlugRouteImport.update({
  id: '/cursos/$courseSlug',
  path: '/cursos/$courseSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const DudasIndexRoute = DudasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DudasRoute,
} as any)
const DudasThreadIdRoute = DudasThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => DudasRoute,
} as any)
const EmpresaIndexRoute = EmpresaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmpresaRoute,
} as any)
const EmpresaCompanySectionRoute = EmpresaCompanySectionRouteImport.update({
  id: '/$companySection',
  path: '/$companySection',
  getParentRoute: () => EmpresaRoute,
} as any)
const EmpresaCodigosRoute = EmpresaCodigosRouteImport.update({
  id: '/codigos',
  path: '/codigos',
  getParentRoute: () => EmpresaRoute,
} as any)
const LegalLegalSlugRoute = LegalLegalSlugRouteImport.update({
  id: '/legal/$legalSlug',
  path: '/legal/$legalSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const PagoConfirmadoRoute = PagoConfirmadoRouteImport.update({
  id: '/pago/confirmado',
  path: '/pago/confirmado',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCursosIndexRoute = AdminCursosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminCursosRoute,
} as any)
const AdminCursosCourseIdRoute = AdminCursosCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => AdminCursosRoute,
} as any)
const ApiCronBillingRoute = ApiCronBillingRouteImport.update({
  id: '/api/cron/billing',
  path: '/api/cron/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusEnrollmentIdIndexRoute = CampusEnrollmentIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CampusEnrollmentIdRoute,
} as any)
const CampusEnrollmentIdConfidencialidadRoute =
  CampusEnrollmentIdConfidencialidadRouteImport.update({
    id: '/confidencialidad',
    path: '/confidencialidad',
    getParentRoute: () => CampusEnrollmentIdRoute,
  } as any)
const EvaluacionEnrollmentIdQuizIdRoute =
  EvaluacionEnrollmentIdQuizIdRouteImport.update({
    id: '/evaluacion/$enrollmentId/$quizId',
    path: '/evaluacion/$enrollmentId/$quizId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalArchivePendingRoute =
  ApiInternalArchivePendingRouteImport.update({
    id: '/api/internal/archive/pending',
    path: '/api/internal/archive/pending',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInvoicesInvoiceIdDownloadRoute =
  ApiInvoicesInvoiceIdDownloadRouteImport.update({
    id: '/$invoiceId/download',
    path: '/$invoiceId/download',
    getParentRoute: () => ApiInvoicesRoute,
  } as any)
const CampusEnrollmentIdLeccionLessonIdRoute =
  CampusEnrollmentIdLeccionLessonIdRouteImport.update({
    id: '/leccion/$lessonId',
    path: '/leccion/$lessonId',
    getParentRoute: () => CampusEnrollmentIdRoute,
  } as any)
const ApiAdminBillingRetryInvoiceIdRoute =
  ApiAdminBillingRetryInvoiceIdRouteImport.update({
    id: '/api/admin/billing/retry/$invoiceId',
    path: '/api/admin/billing/retry/$invoiceId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalArchiveInvoiceIdConfirmRoute =
  ApiInternalArchiveInvoiceIdConfirmRouteImport.update({
    id: '/api/internal/archive/$invoiceId/confirm',
    path: '/api/internal/archive/$invoiceId/confirm',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalArchiveInvoiceIdDownloadRoute =
  ApiInternalArchiveInvoiceIdDownloadRouteImport.update({
    id: '/api/internal/archive/$invoiceId/download',
    path: '/api/internal/archive/$invoiceId/download',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalArchiveInvoiceIdFailRoute =
  ApiInternalArchiveInvoiceIdFailRouteImport.update({
    id: '/api/internal/archive/$invoiceId/fail',
    path: '/api/internal/archive/$invoiceId/fail',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acceso': typeof AccesoRoute
  '/admin': typeof AdminRouteWithChildren
  '/canjear-codigo': typeof CanjearCodigoRoute
  '/catalogo': typeof CatalogoRoute
  '/certificados': typeof CertificadosRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contacto': typeof ContactoRoute
  '/dudas': typeof DudasRouteWithChildren
  '/empresa': typeof EmpresaRouteWithChildren
  '/empresas': typeof EmpresasRoute
  '/facturas': typeof FacturasRoute
  '/formacion-preventiva-oficial': typeof FormacionPreventivaOficialRoute
  '/mis-cursos': typeof MisCursosRoute
  '/nueva-contrasena': typeof NuevaContrasenaRoute
  '/perfil': typeof PerfilRoute
  '/recuperar-contrasena': typeof RecuperarContrasenaRoute
  '/registro': typeof RegistroRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/verificar-certificado': typeof VerificarCertificadoRoute
  '/admin/$adminSection': typeof AdminAdminSectionRoute
  '/admin/codigos': typeof AdminCodigosRoute
  '/admin/cursos': typeof AdminCursosRouteWithChildren
  '/admin/evaluaciones': typeof AdminEvaluacionesRoute
  '/admin/facturacion': typeof AdminFacturacionRoute
  '/admin/mensajes': typeof AdminMensajesRoute
  '/admin/practicas': typeof AdminPracticasRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/api/admin-billing': typeof ApiAdminBillingRoute
  '/api/certificado-stvh': typeof ApiCertificadoStvhRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/company-access-codes': typeof ApiCompanyAccessCodesRoute
  '/api/invoices': typeof ApiInvoicesRouteWithChildren
  '/api/payment-status': typeof ApiPaymentStatusRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/campus/$enrollmentId': typeof CampusEnrollmentIdRouteWithChildren
  '/comprar-empresa/$courseSlug': typeof ComprarEmpresaCourseSlugRoute
  '/comprar/$courseSlug': typeof ComprarCourseSlugRoute
  '/cursos/$courseSlug': typeof CursosCourseSlugRoute
  '/dudas/$threadId': typeof DudasThreadIdRoute
  '/empresa/$companySection': typeof EmpresaCompanySectionRoute
  '/empresa/codigos': typeof EmpresaCodigosRoute
  '/legal/$legalSlug': typeof LegalLegalSlugRoute
  '/pago/confirmado': typeof PagoConfirmadoRoute
  '/admin/': typeof AdminIndexRoute
  '/dudas/': typeof DudasIndexRoute
  '/empresa/': typeof EmpresaIndexRoute
  '/admin/cursos/$courseId': typeof AdminCursosCourseIdRoute
  '/api/cron/billing': typeof ApiCronBillingRoute
  '/campus/$enrollmentId/confidencialidad': typeof CampusEnrollmentIdConfidencialidadRoute
  '/evaluacion/$enrollmentId/$quizId': typeof EvaluacionEnrollmentIdQuizIdRoute
  '/admin/cursos/': typeof AdminCursosIndexRoute
  '/campus/$enrollmentId/': typeof CampusEnrollmentIdIndexRoute
  '/api/internal/archive/pending': typeof ApiInternalArchivePendingRoute
  '/api/invoices/$invoiceId/download': typeof ApiInvoicesInvoiceIdDownloadRoute
  '/campus/$enrollmentId/leccion/$lessonId': typeof CampusEnrollmentIdLeccionLessonIdRoute
  '/api/admin/billing/retry/$invoiceId': typeof ApiAdminBillingRetryInvoiceIdRoute
  '/api/internal/archive/$invoiceId/confirm': typeof ApiInternalArchiveInvoiceIdConfirmRoute
  '/api/internal/archive/$invoiceId/download': typeof ApiInternalArchiveInvoiceIdDownloadRoute
  '/api/internal/archive/$invoiceId/fail': typeof ApiInternalArchiveInvoiceIdFailRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acceso': typeof AccesoRoute
  '/canjear-codigo': typeof CanjearCodigoRoute
  '/catalogo': typeof CatalogoRoute
  '/certificados': typeof CertificadosRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contacto': typeof ContactoRoute
  '/empresas': typeof EmpresasRoute
  '/facturas': typeof FacturasRoute
  '/formacion-preventiva-oficial': typeof FormacionPreventivaOficialRoute
  '/mis-cursos': typeof MisCursosRoute
  '/nueva-contrasena': typeof NuevaContrasenaRoute
  '/perfil': typeof PerfilRoute
  '/recuperar-contrasena': typeof RecuperarContrasenaRoute
  '/registro': typeof RegistroRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/verificar-certificado': typeof VerificarCertificadoRoute
  '/admin/$adminSection': typeof AdminAdminSectionRoute
  '/admin/codigos': typeof AdminCodigosRoute
  '/admin/evaluaciones': typeof AdminEvaluacionesRoute
  '/admin/facturacion': typeof AdminFacturacionRoute
  '/admin/mensajes': typeof AdminMensajesRoute
  '/admin/practicas': typeof AdminPracticasRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/api/admin-billing': typeof ApiAdminBillingRoute
  '/api/certificado-stvh': typeof ApiCertificadoStvhRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/company-access-codes': typeof ApiCompanyAccessCodesRoute
  '/api/invoices': typeof ApiInvoicesRouteWithChildren
  '/api/payment-status': typeof ApiPaymentStatusRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/comprar-empresa/$courseSlug': typeof ComprarEmpresaCourseSlugRoute
  '/comprar/$courseSlug': typeof ComprarCourseSlugRoute
  '/cursos/$courseSlug': typeof CursosCourseSlugRoute
  '/dudas/$threadId': typeof DudasThreadIdRoute
  '/empresa/$companySection': typeof EmpresaCompanySectionRoute
  '/empresa/codigos': typeof EmpresaCodigosRoute
  '/legal/$legalSlug': typeof LegalLegalSlugRoute
  '/pago/confirmado': typeof PagoConfirmadoRoute
  '/admin': typeof AdminIndexRoute
  '/dudas': typeof DudasIndexRoute
  '/empresa': typeof EmpresaIndexRoute
  '/admin/cursos/$courseId': typeof AdminCursosCourseIdRoute
  '/api/cron/billing': typeof ApiCronBillingRoute
  '/campus/$enrollmentId/confidencialidad': typeof CampusEnrollmentIdConfidencialidadRoute
  '/evaluacion/$enrollmentId/$quizId': typeof EvaluacionEnrollmentIdQuizIdRoute
  '/admin/cursos': typeof AdminCursosIndexRoute
  '/campus/$enrollmentId': typeof CampusEnrollmentIdIndexRoute
  '/api/internal/archive/pending': typeof ApiInternalArchivePendingRoute
  '/api/invoices/$invoiceId/download': typeof ApiInvoicesInvoiceIdDownloadRoute
  '/campus/$enrollmentId/leccion/$lessonId': typeof CampusEnrollmentIdLeccionLessonIdRoute
  '/api/admin/billing/retry/$invoiceId': typeof ApiAdminBillingRetryInvoiceIdRoute
  '/api/internal/archive/$invoiceId/confirm': typeof ApiInternalArchiveInvoiceIdConfirmRoute
  '/api/internal/archive/$invoiceId/download': typeof ApiInternalArchiveInvoiceIdDownloadRoute
  '/api/internal/archive/$invoiceId/fail': typeof ApiInternalArchiveInvoiceIdFailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acceso': typeof AccesoRoute
  '/admin': typeof AdminRouteWithChildren
  '/canjear-codigo': typeof CanjearCodigoRoute
  '/catalogo': typeof CatalogoRoute
  '/certificados': typeof CertificadosRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contacto': typeof ContactoRoute
  '/dudas': typeof DudasRouteWithChildren
  '/empresa': typeof EmpresaRouteWithChildren
  '/empresas': typeof EmpresasRoute
  '/facturas': typeof FacturasRoute
  '/formacion-preventiva-oficial': typeof FormacionPreventivaOficialRoute
  '/mis-cursos': typeof MisCursosRoute
  '/nueva-contrasena': typeof NuevaContrasenaRoute
  '/perfil': typeof PerfilRoute
  '/recuperar-contrasena': typeof RecuperarContrasenaRoute
  '/registro': typeof RegistroRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/verificar-certificado': typeof VerificarCertificadoRoute
  '/admin/$adminSection': typeof AdminAdminSectionRoute
  '/admin/codigos': typeof AdminCodigosRoute
  '/admin/cursos': typeof AdminCursosRouteWithChildren
  '/admin/evaluaciones': typeof AdminEvaluacionesRoute
  '/admin/facturacion': typeof AdminFacturacionRoute
  '/admin/mensajes': typeof AdminMensajesRoute
  '/admin/practicas': typeof AdminPracticasRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/api/admin-billing': typeof ApiAdminBillingRoute
  '/api/certificado-stvh': typeof ApiCertificadoStvhRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/company-access-codes': typeof ApiCompanyAccessCodesRoute
  '/api/invoices': typeof ApiInvoicesRouteWithChildren
  '/api/payment-status': typeof ApiPaymentStatusRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/campus/$enrollmentId': typeof CampusEnrollmentIdRouteWithChildren
  '/comprar-empresa/$courseSlug': typeof ComprarEmpresaCourseSlugRoute
  '/comprar/$courseSlug': typeof ComprarCourseSlugRoute
  '/cursos/$courseSlug': typeof CursosCourseSlugRoute
  '/dudas/$threadId': typeof DudasThreadIdRoute
  '/empresa/$companySection': typeof EmpresaCompanySectionRoute
  '/empresa/codigos': typeof EmpresaCodigosRoute
  '/legal/$legalSlug': typeof LegalLegalSlugRoute
  '/pago/confirmado': typeof PagoConfirmadoRoute
  '/admin/': typeof AdminIndexRoute
  '/dudas/': typeof DudasIndexRoute
  '/empresa/': typeof EmpresaIndexRoute
  '/admin/cursos/$courseId': typeof AdminCursosCourseIdRoute
  '/api/cron/billing': typeof ApiCronBillingRoute
  '/campus/$enrollmentId/confidencialidad': typeof CampusEnrollmentIdConfidencialidadRoute
  '/evaluacion/$enrollmentId/$quizId': typeof EvaluacionEnrollmentIdQuizIdRoute
  '/admin/cursos/': typeof AdminCursosIndexRoute
  '/campus/$enrollmentId/': typeof CampusEnrollmentIdIndexRoute
  '/api/internal/archive/pending': typeof ApiInternalArchivePendingRoute
  '/api/invoices/$invoiceId/download': typeof ApiInvoicesInvoiceIdDownloadRoute
  '/campus/$enrollmentId/leccion/$lessonId': typeof CampusEnrollmentIdLeccionLessonIdRoute
  '/api/admin/billing/retry/$invoiceId': typeof ApiAdminBillingRetryInvoiceIdRoute
  '/api/internal/archive/$invoiceId/confirm': typeof ApiInternalArchiveInvoiceIdConfirmRoute
  '/api/internal/archive/$invoiceId/download': typeof ApiInternalArchiveInvoiceIdDownloadRoute
  '/api/internal/archive/$invoiceId/fail': typeof ApiInternalArchiveInvoiceIdFailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acceso'
    | '/admin'
    | '/canjear-codigo'
    | '/catalogo'
    | '/certificados'
    | '/como-funciona'
    | '/contacto'
    | '/dudas'
    | '/empresa'
    | '/empresas'
    | '/facturas'
    | '/formacion-preventiva-oficial'
    | '/mis-cursos'
    | '/nueva-contrasena'
    | '/perfil'
    | '/recuperar-contrasena'
    | '/registro'
    | '/sobre-nosotros'
    | '/verificar-certificado'
    | '/admin/$adminSection'
    | '/admin/codigos'
    | '/admin/cursos'
    | '/admin/evaluaciones'
    | '/admin/facturacion'
    | '/admin/mensajes'
    | '/admin/practicas'
    | '/admin/usuarios'
    | '/api/admin-billing'
    | '/api/certificado-stvh'
    | '/api/checkout'
    | '/api/company-access-codes'
    | '/api/invoices'
    | '/api/payment-status'
    | '/api/stripe-webhook'
    | '/campus/$enrollmentId'
    | '/comprar-empresa/$courseSlug'
    | '/comprar/$courseSlug'
    | '/cursos/$courseSlug'
    | '/dudas/$threadId'
    | '/empresa/$companySection'
    | '/empresa/codigos'
    | '/legal/$legalSlug'
    | '/pago/confirmado'
    | '/admin/'
    | '/dudas/'
    | '/empresa/'
    | '/admin/cursos/$courseId'
    | '/api/cron/billing'
    | '/campus/$enrollmentId/confidencialidad'
    | '/evaluacion/$enrollmentId/$quizId'
    | '/admin/cursos/'
    | '/campus/$enrollmentId/'
    | '/api/internal/archive/pending'
    | '/api/invoices/$invoiceId/download'
    | '/campus/$enrollmentId/leccion/$lessonId'
    | '/api/admin/billing/retry/$invoiceId'
    | '/api/internal/archive/$invoiceId/confirm'
    | '/api/internal/archive/$invoiceId/download'
    | '/api/internal/archive/$invoiceId/fail'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acceso'
    | '/canjear-codigo'
    | '/catalogo'
    | '/certificados'
    | '/como-funciona'
    | '/contacto'
    | '/empresas'
    | '/facturas'
    | '/formacion-preventiva-oficial'
    | '/mis-cursos'
    | '/nueva-contrasena'
    | '/perfil'
    | '/recuperar-contrasena'
    | '/registro'
    | '/sobre-nosotros'
    | '/verificar-certificado'
    | '/admin/$adminSection'
    | '/admin/codigos'
    | '/admin/evaluaciones'
    | '/admin/facturacion'
    | '/admin/mensajes'
    | '/admin/practicas'
    | '/admin/usuarios'
    | '/api/admin-billing'
    | '/api/certificado-stvh'
    | '/api/checkout'
    | '/api/company-access-codes'
    | '/api/invoices'
    | '/api/payment-status'
    | '/api/stripe-webhook'
    | '/comprar-empresa/$courseSlug'
    | '/comprar/$courseSlug'
    | '/cursos/$courseSlug'
    | '/dudas/$threadId'
    | '/empresa/$companySection'
    | '/empresa/codigos'
    | '/legal/$legalSlug'
    | '/pago/confirmado'
    | '/admin'
    | '/dudas'
    | '/empresa'
    | '/admin/cursos/$courseId'
    | '/api/cron/billing'
    | '/campus/$enrollmentId/confidencialidad'
    | '/evaluacion/$enrollmentId/$quizId'
    | '/admin/cursos'
    | '/campus/$enrollmentId'
    | '/api/internal/archive/pending'
    | '/api/invoices/$invoiceId/download'
    | '/campus/$enrollmentId/leccion/$lessonId'
    | '/api/admin/billing/retry/$invoiceId'
    | '/api/internal/archive/$invoiceId/confirm'
    | '/api/internal/archive/$invoiceId/download'
    | '/api/internal/archive/$invoiceId/fail'
  id:
    | '__root__'
    | '/'
    | '/acceso'
    | '/admin'
    | '/canjear-codigo'
    | '/catalogo'
    | '/certificados'
    | '/como-funciona'
    | '/contacto'
    | '/dudas'
    | '/empresa'
    | '/empresas'
    | '/facturas'
    | '/formacion-preventiva-oficial'
    | '/mis-cursos'
    | '/nueva-contrasena'
    | '/perfil'
    | '/recuperar-contrasena'
    | '/registro'
    | '/sobre-nosotros'
    | '/verificar-certificado'
    | '/admin/$adminSection'
    | '/admin/codigos'
    | '/admin/cursos'
    | '/admin/evaluaciones'
    | '/admin/facturacion'
    | '/admin/mensajes'
    | '/admin/practicas'
    | '/admin/usuarios'
    | '/api/admin-billing'
    | '/api/certificado-stvh'
    | '/api/checkout'
    | '/api/company-access-codes'
    | '/api/invoices'
    | '/api/payment-status'
    | '/api/stripe-webhook'
    | '/campus/$enrollmentId'
    | '/comprar-empresa/$courseSlug'
    | '/comprar/$courseSlug'
    | '/cursos/$courseSlug'
    | '/dudas/$threadId'
    | '/empresa/$companySection'
    | '/empresa/codigos'
    | '/legal/$legalSlug'
    | '/pago/confirmado'
    | '/admin/'
    | '/dudas/'
    | '/empresa/'
    | '/admin/cursos/$courseId'
    | '/api/cron/billing'
    | '/campus/$enrollmentId/confidencialidad'
    | '/evaluacion/$enrollmentId/$quizId'
    | '/admin/cursos/'
    | '/campus/$enrollmentId/'
    | '/api/internal/archive/pending'
    | '/api/invoices/$invoiceId/download'
    | '/campus/$enrollmentId/leccion/$lessonId'
    | '/api/admin/billing/retry/$invoiceId'
    | '/api/internal/archive/$invoiceId/confirm'
    | '/api/internal/archive/$invoiceId/download'
    | '/api/internal/archive/$invoiceId/fail'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccesoRoute: typeof AccesoRoute
  AdminRoute: typeof AdminRouteWithChildren
  CanjearCodigoRoute: typeof CanjearCodigoRoute
  CatalogoRoute: typeof CatalogoRoute
  CertificadosRoute: typeof CertificadosRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  ContactoRoute: typeof ContactoRoute
  DudasRoute: typeof DudasRouteWithChildren
  EmpresaRoute: typeof EmpresaRouteWithChildren
  EmpresasRoute: typeof EmpresasRoute
  FacturasRoute: typeof FacturasRoute
  FormacionPreventivaOficialRoute: typeof FormacionPreventivaOficialRoute
  MisCursosRoute: typeof MisCursosRoute
  NuevaContrasenaRoute: typeof NuevaContrasenaRoute
  PerfilRoute: typeof PerfilRoute
  RecuperarContrasenaRoute: typeof RecuperarContrasenaRoute
  RegistroRoute: typeof RegistroRoute
  SobreNosotrosRoute: typeof SobreNosotrosRoute
  VerificarCertificadoRoute: typeof VerificarCertificadoRoute
  ApiAdminBillingRoute: typeof ApiAdminBillingRoute
  ApiCertificadoStvhRoute: typeof ApiCertificadoStvhRoute
  ApiCheckoutRoute: typeof ApiCheckoutRoute
  ApiCompanyAccessCodesRoute: typeof ApiCompanyAccessCodesRoute
  ApiInvoicesRoute: typeof ApiInvoicesRouteWithChildren
  ApiPaymentStatusRoute: typeof ApiPaymentStatusRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  CampusEnrollmentIdRoute: typeof CampusEnrollmentIdRouteWithChildren
  ComprarEmpresaCourseSlugRoute: typeof ComprarEmpresaCourseSlugRoute
  ComprarCourseSlugRoute: typeof ComprarCourseSlugRoute
  CursosCourseSlugRoute: typeof CursosCourseSlugRoute
  LegalLegalSlugRoute: typeof LegalLegalSlugRoute
  PagoConfirmadoRoute: typeof PagoConfirmadoRoute
  ApiCronBillingRoute: typeof ApiCronBillingRoute
  EvaluacionEnrollmentIdQuizIdRoute: typeof EvaluacionEnrollmentIdQuizIdRoute
  ApiInternalArchivePendingRoute: typeof ApiInternalArchivePendingRoute
  ApiAdminBillingRetryInvoiceIdRoute: typeof ApiAdminBillingRetryInvoiceIdRoute
  ApiInternalArchiveInvoiceIdConfirmRoute: typeof ApiInternalArchiveInvoiceIdConfirmRoute
  ApiInternalArchiveInvoiceIdDownloadRoute: typeof ApiInternalArchiveInvoiceIdDownloadRoute
  ApiInternalArchiveInvoiceIdFailRoute: typeof ApiInternalArchiveInvoiceIdFailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acceso': {
      id: '/acceso'
      path: '/acceso'
      fullPath: '/acceso'
      preLoaderRoute: typeof AccesoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canjear-codigo': {
      id: '/canjear-codigo'
      path: '/canjear-codigo'
      fullPath: '/canjear-codigo'
      preLoaderRoute: typeof CanjearCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificados': {
      id: '/certificados'
      path: '/certificados'
      fullPath: '/certificados'
      preLoaderRoute: typeof CertificadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dudas': {
      id: '/dudas'
      path: '/dudas'
      fullPath: '/dudas'
      preLoaderRoute: typeof DudasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa': {
      id: '/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof EmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas': {
      id: '/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof EmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facturas': {
      id: '/facturas'
      path: '/facturas'
      fullPath: '/facturas'
      preLoaderRoute: typeof FacturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formacion-preventiva-oficial': {
      id: '/formacion-preventiva-oficial'
      path: '/formacion-preventiva-oficial'
      fullPath: '/formacion-preventiva-oficial'
      preLoaderRoute: typeof FormacionPreventivaOficialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mis-cursos': {
      id: '/mis-cursos'
      path: '/mis-cursos'
      fullPath: '/mis-cursos'
      preLoaderRoute: typeof MisCursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nueva-contrasena': {
      id: '/nueva-contrasena'
      path: '/nueva-contrasena'
      fullPath: '/nueva-contrasena'
      preLoaderRoute: typeof NuevaContrasenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-contrasena': {
      id: '/recuperar-contrasena'
      path: '/recuperar-contrasena'
      fullPath: '/recuperar-contrasena'
      preLoaderRoute: typeof RecuperarContrasenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-nosotros': {
      id: '/sobre-nosotros'
      path: '/sobre-nosotros'
      fullPath: '/sobre-nosotros'
      preLoaderRoute: typeof SobreNosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verificar-certificado': {
      id: '/verificar-certificado'
      path: '/verificar-certificado'
      fullPath: '/verificar-certificado'
      preLoaderRoute: typeof VerificarCertificadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/$adminSection': {
      id: '/admin/$adminSection'
      path: '/$adminSection'
      fullPath: '/admin/$adminSection'
      preLoaderRoute: typeof AdminAdminSectionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/codigos': {
      id: '/admin/codigos'
      path: '/codigos'
      fullPath: '/admin/codigos'
      preLoaderRoute: typeof AdminCodigosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cursos': {
      id: '/admin/cursos'
      path: '/cursos'
      fullPath: '/admin/cursos'
      preLoaderRoute: typeof AdminCursosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/evaluaciones': {
      id: '/admin/evaluaciones'
      path: '/evaluaciones'
      fullPath: '/admin/evaluaciones'
      preLoaderRoute: typeof AdminEvaluacionesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/facturacion': {
      id: '/admin/facturacion'
      path: '/facturacion'
      fullPath: '/admin/facturacion'
      preLoaderRoute: typeof AdminFacturacionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mensajes': {
      id: '/admin/mensajes'
      path: '/mensajes'
      fullPath: '/admin/mensajes'
      preLoaderRoute: typeof AdminMensajesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/practicas': {
      id: '/admin/practicas'
      path: '/practicas'
      fullPath: '/admin/practicas'
      preLoaderRoute: typeof AdminPracticasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/admin-billing': {
      id: '/api/admin-billing'
      path: '/api/admin-billing'
      fullPath: '/api/admin-billing'
      preLoaderRoute: typeof ApiAdminBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/certificado-stvh': {
      id: '/api/certificado-stvh'
      path: '/api/certificado-stvh'
      fullPath: '/api/certificado-stvh'
      preLoaderRoute: typeof ApiCertificadoStvhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout': {
      id: '/api/checkout'
      path: '/api/checkout'
      fullPath: '/api/checkout'
      preLoaderRoute: typeof ApiCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/company-access-codes': {
      id: '/api/company-access-codes'
      path: '/api/company-access-codes'
      fullPath: '/api/company-access-codes'
      preLoaderRoute: typeof ApiCompanyAccessCodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invoices': {
      id: '/api/invoices'
      path: '/api/invoices'
      fullPath: '/api/invoices'
      preLoaderRoute: typeof ApiInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment-status': {
      id: '/api/payment-status'
      path: '/api/payment-status'
      fullPath: '/api/payment-status'
      preLoaderRoute: typeof ApiPaymentStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe-webhook': {
      id: '/api/stripe-webhook'
      path: '/api/stripe-webhook'
      fullPath: '/api/stripe-webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus/$enrollmentId': {
      id: '/campus/$enrollmentId'
      path: '/campus/$enrollmentId'
      fullPath: '/campus/$enrollmentId'
      preLoaderRoute: typeof CampusEnrollmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comprar-empresa/$courseSlug': {
      id: '/comprar-empresa/$courseSlug'
      path: '/comprar-empresa/$courseSlug'
      fullPath: '/comprar-empresa/$courseSlug'
      preLoaderRoute: typeof ComprarEmpresaCourseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comprar/$courseSlug': {
      id: '/comprar/$courseSlug'
      path: '/comprar/$courseSlug'
      fullPath: '/comprar/$courseSlug'
      preLoaderRoute: typeof ComprarCourseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/$courseSlug': {
      id: '/cursos/$courseSlug'
      path: '/cursos/$courseSlug'
      fullPath: '/cursos/$courseSlug'
      preLoaderRoute: typeof CursosCourseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dudas/': {
      id: '/dudas/'
      path: '/'
      fullPath: '/dudas/'
      preLoaderRoute: typeof DudasIndexRouteImport
      parentRoute: typeof DudasRoute
    }
    '/dudas/$threadId': {
      id: '/dudas/$threadId'
      path: '/$threadId'
      fullPath: '/dudas/$threadId'
      preLoaderRoute: typeof DudasThreadIdRouteImport
      parentRoute: typeof DudasRoute
    }
    '/empresa/': {
      id: '/empresa/'
      path: '/'
      fullPath: '/empresa/'
      preLoaderRoute: typeof EmpresaIndexRouteImport
      parentRoute: typeof EmpresaRoute
    }
    '/empresa/$companySection': {
      id: '/empresa/$companySection'
      path: '/$companySection'
      fullPath: '/empresa/$companySection'
      preLoaderRoute: typeof EmpresaCompanySectionRouteImport
      parentRoute: typeof EmpresaRoute
    }
    '/empresa/codigos': {
      id: '/empresa/codigos'
      path: '/codigos'
      fullPath: '/empresa/codigos'
      preLoaderRoute: typeof EmpresaCodigosRouteImport
      parentRoute: typeof EmpresaRoute
    }
    '/legal/$legalSlug': {
      id: '/legal/$legalSlug'
      path: '/legal/$legalSlug'
      fullPath: '/legal/$legalSlug'
      preLoaderRoute: typeof LegalLegalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pago/confirmado': {
      id: '/pago/confirmado'
      path: '/pago/confirmado'
      fullPath: '/pago/confirmado'
      preLoaderRoute: typeof PagoConfirmadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cursos/': {
      id: '/admin/cursos/'
      path: '/'
      fullPath: '/admin/cursos/'
      preLoaderRoute: typeof AdminCursosIndexRouteImport
      parentRoute: typeof AdminCursosRoute
    }
    '/admin/cursos/$courseId': {
      id: '/admin/cursos/$courseId'
      path: '/$courseId'
      fullPath: '/admin/cursos/$courseId'
      preLoaderRoute: typeof AdminCursosCourseIdRouteImport
      parentRoute: typeof AdminCursosRoute
    }
    '/api/cron/billing': {
      id: '/api/cron/billing'
      path: '/api/cron/billing'
      fullPath: '/api/cron/billing'
      preLoaderRoute: typeof ApiCronBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus/$enrollmentId/': {
      id: '/campus/$enrollmentId/'
      path: '/'
      fullPath: '/campus/$enrollmentId/'
      preLoaderRoute: typeof CampusEnrollmentIdIndexRouteImport
      parentRoute: typeof CampusEnrollmentIdRoute
    }
    '/campus/$enrollmentId/confidencialidad': {
      id: '/campus/$enrollmentId/confidencialidad'
      path: '/confidencialidad'
      fullPath: '/campus/$enrollmentId/confidencialidad'
      preLoaderRoute: typeof CampusEnrollmentIdConfidencialidadRouteImport
      parentRoute: typeof CampusEnrollmentIdRoute
    }
    '/evaluacion/$enrollmentId/$quizId': {
      id: '/evaluacion/$enrollmentId/$quizId'
      path: '/evaluacion/$enrollmentId/$quizId'
      fullPath: '/evaluacion/$enrollmentId/$quizId'
      preLoaderRoute: typeof EvaluacionEnrollmentIdQuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/archive/pending': {
      id: '/api/internal/archive/pending'
      path: '/api/internal/archive/pending'
      fullPath: '/api/internal/archive/pending'
      preLoaderRoute: typeof ApiInternalArchivePendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invoices/$invoiceId/download': {
      id: '/api/invoices/$invoiceId/download'
      path: '/$invoiceId/download'
      fullPath: '/api/invoices/$invoiceId/download'
      preLoaderRoute: typeof ApiInvoicesInvoiceIdDownloadRouteImport
      parentRoute: typeof ApiInvoicesRoute
    }
    '/campus/$enrollmentId/leccion/$lessonId': {
      id: '/campus/$enrollmentId/leccion/$lessonId'
      path: '/leccion/$lessonId'
      fullPath: '/campus/$enrollmentId/leccion/$lessonId'
      preLoaderRoute: typeof CampusEnrollmentIdLeccionLessonIdRouteImport
      parentRoute: typeof CampusEnrollmentIdRoute
    }
    '/api/admin/billing/retry/$invoiceId': {
      id: '/api/admin/billing/retry/$invoiceId'
      path: '/api/admin/billing/retry/$invoiceId'
      fullPath: '/api/admin/billing/retry/$invoiceId'
      preLoaderRoute: typeof ApiAdminBillingRetryInvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/archive/$invoiceId/confirm': {
      id: '/api/internal/archive/$invoiceId/confirm'
      path: '/api/internal/archive/$invoiceId/confirm'
      fullPath: '/api/internal/archive/$invoiceId/confirm'
      preLoaderRoute: typeof ApiInternalArchiveInvoiceIdConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/archive/$invoiceId/download': {
      id: '/api/internal/archive/$invoiceId/download'
      path: '/api/internal/archive/$invoiceId/download'
      fullPath: '/api/internal/archive/$invoiceId/download'
      preLoaderRoute: typeof ApiInternalArchiveInvoiceIdDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/archive/$invoiceId/fail': {
      id: '/api/internal/archive/$invoiceId/fail'
      path: '/api/internal/archive/$invoiceId/fail'
      fullPath: '/api/internal/archive/$invoiceId/fail'
      preLoaderRoute: typeof ApiInternalArchiveInvoiceIdFailRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminCursosRouteChildren {
  AdminCursosCourseIdRoute: typeof AdminCursosCourseIdRoute
  AdminCursosIndexRoute: typeof AdminCursosIndexRoute
}

const AdminCursosRouteChildren: AdminCursosRouteChildren = {
  AdminCursosCourseIdRoute: AdminCursosCourseIdRoute,
  AdminCursosIndexRoute: AdminCursosIndexRoute,
}

const AdminCursosRouteWithChildren = AdminCursosRoute._addFileChildren(
  AdminCursosRouteChildren,
)

interface AdminRouteChildren {
  AdminAdminSectionRoute: typeof AdminAdminSectionRoute
  AdminCodigosRoute: typeof AdminCodigosRoute
  AdminCursosRoute: typeof AdminCursosRouteWithChildren
  AdminEvaluacionesRoute: typeof AdminEvaluacionesRoute
  AdminFacturacionRoute: typeof AdminFacturacionRoute
  AdminMensajesRoute: typeof AdminMensajesRoute
  AdminPracticasRoute: typeof AdminPracticasRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminSectionRoute: AdminAdminSectionRoute,
  AdminCodigosRoute: AdminCodigosRoute,
  AdminCursosRoute: AdminCursosRouteWithChildren,
  AdminEvaluacionesRoute: AdminEvaluacionesRoute,
  AdminFacturacionRoute: AdminFacturacionRoute,
  AdminMensajesRoute: AdminMensajesRoute,
  AdminPracticasRoute: AdminPracticasRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DudasRouteChildren {
  DudasThreadIdRoute: typeof DudasThreadIdRoute
  DudasIndexRoute: typeof DudasIndexRoute
}

const DudasRouteChildren: DudasRouteChildren = {
  DudasThreadIdRoute: DudasThreadIdRoute,
  DudasIndexRoute: DudasIndexRoute,
}

const DudasRouteWithChildren = DudasRoute._addFileChildren(DudasRouteChildren)

interface EmpresaRouteChildren {
  EmpresaCompanySectionRoute: typeof EmpresaCompanySectionRoute
  EmpresaCodigosRoute: typeof EmpresaCodigosRoute
  EmpresaIndexRoute: typeof EmpresaIndexRoute
}

const EmpresaRouteChildren: EmpresaRouteChildren = {
  EmpresaCompanySectionRoute: EmpresaCompanySectionRoute,
  EmpresaCodigosRoute: EmpresaCodigosRoute,
  EmpresaIndexRoute: EmpresaIndexRoute,
}

const EmpresaRouteWithChildren =
  EmpresaRoute._addFileChildren(EmpresaRouteChildren)

interface ApiInvoicesRouteChildren {
  ApiInvoicesInvoiceIdDownloadRoute: typeof ApiInvoicesInvoiceIdDownloadRoute
}

const ApiInvoicesRouteChildren: ApiInvoicesRouteChildren = {
  ApiInvoicesInvoiceIdDownloadRoute: ApiInvoicesInvoiceIdDownloadRoute,
}

const ApiInvoicesRouteWithChildren = ApiInvoicesRoute._addFileChildren(
  ApiInvoicesRouteChildren,
)

interface CampusEnrollmentIdRouteChildren {
  CampusEnrollmentIdConfidencialidadRoute: typeof CampusEnrollmentIdConfidencialidadRoute
  CampusEnrollmentIdIndexRoute: typeof CampusEnrollmentIdIndexRoute
  CampusEnrollmentIdLeccionLessonIdRoute: typeof CampusEnrollmentIdLeccionLessonIdRoute
}

const CampusEnrollmentIdRouteChildren: CampusEnrollmentIdRouteChildren = {
  CampusEnrollmentIdConfidencialidadRoute:
    CampusEnrollmentIdConfidencialidadRoute,
  CampusEnrollmentIdIndexRoute: CampusEnrollmentIdIndexRoute,
  CampusEnrollmentIdLeccionLessonIdRoute:
    CampusEnrollmentIdLeccionLessonIdRoute,
}

const CampusEnrollmentIdRouteWithChildren =
  CampusEnrollmentIdRoute._addFileChildren(CampusEnrollmentIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccesoRoute: AccesoRoute,
  AdminRoute: AdminRouteWithChildren,
  CanjearCodigoRoute: CanjearCodigoRoute,
  CatalogoRoute: CatalogoRoute,
  CertificadosRoute: CertificadosRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  ContactoRoute: ContactoRoute,
  DudasRoute: DudasRouteWithChildren,
  EmpresaRoute: EmpresaRouteWithChildren,
  EmpresasRoute: EmpresasRoute,
  FacturasRoute: FacturasRoute,
  FormacionPreventivaOficialRoute: FormacionPreventivaOficialRoute,
  MisCursosRoute: MisCursosRoute,
  NuevaContrasenaRoute: NuevaContrasenaRoute,
  PerfilRoute: PerfilRoute,
  RecuperarContrasenaRoute: RecuperarContrasenaRoute,
  RegistroRoute: RegistroRoute,
  SobreNosotrosRoute: SobreNosotrosRoute,
  VerificarCertificadoRoute: VerificarCertificadoRoute,
  ApiAdminBillingRoute: ApiAdminBillingRoute,
  ApiCertificadoStvhRoute: ApiCertificadoStvhRoute,
  ApiCheckoutRoute: ApiCheckoutRoute,
  ApiCompanyAccessCodesRoute: ApiCompanyAccessCodesRoute,
  ApiInvoicesRoute: ApiInvoicesRouteWithChildren,
  ApiPaymentStatusRoute: ApiPaymentStatusRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  CampusEnrollmentIdRoute: CampusEnrollmentIdRouteWithChildren,
  ComprarEmpresaCourseSlugRoute: ComprarEmpresaCourseSlugRoute,
  ComprarCourseSlugRoute: ComprarCourseSlugRoute,
  CursosCourseSlugRoute: CursosCourseSlugRoute,
  LegalLegalSlugRoute: LegalLegalSlugRoute,
  PagoConfirmadoRoute: PagoConfirmadoRoute,
  ApiCronBillingRoute: ApiCronBillingRoute,
  EvaluacionEnrollmentIdQuizIdRoute: EvaluacionEnrollmentIdQuizIdRoute,
  ApiInternalArchivePendingRoute: ApiInternalArchivePendingRoute,
  ApiAdminBillingRetryInvoiceIdRoute: ApiAdminBillingRetryInvoiceIdRoute,
  ApiInternalArchiveInvoiceIdConfirmRoute:
    ApiInternalArchiveInvoiceIdConfirmRoute,
  ApiInternalArchiveInvoiceIdDownloadRoute:
    ApiInternalArchiveInvoiceIdDownloadRoute,
  ApiInternalArchiveInvoiceIdFailRoute: ApiInternalArchiveInvoiceIdFailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
